site_name: Gravity Madness
pages:
    - Wstęp: index.md
    - Teoria: theory.md
    - Moduły: modules.md
    - Klasy: classes.md
    - Rozgrywka: gameplay.md
    - Statki: spaceships.md
    - Kontrolery: controllers.md
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math